FROM ubuntu:20.04

# 1. docker install
WORKDIR /usr/src/builder

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Seoul

RUN apt update -y

RUN apt install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    apt-transport-https \
    sudo

# RUN sudo echo -e "search 8.8.4.4\nnameserver 8.8.8.8" > /etc/resolv.conf

RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt update -y

RUN apt install -y \
    docker-ce \
    docker-ce-cli

# 2. script, env file copy
# COPY ./build_script.py /apps/build_script.py
# COPY ./requirements.txt /apps/requirements.txt

# 3. python install
RUN apt install -y python3.8 python3-pip &&\
    python3.8 -m pip install --upgrade pip

RUN apt install git

# ARG DISABLE_CACHE

COPY build.sh /apps/build.sh

# RUN pip3 install -r /apps/requirements.txt

# # 4. bentoml bundling & containerizing
# ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

# RUN python3.8 /apps/build_script.py &&\
#     bentoml containerize TransformerService:latest -t build_testing:v1